### PR TITLE
Enchantment of str class #247 - Adds hasUpercase and hasLowercase function with tests

### PR DESCRIPTION
**Pull request by hasukmistry**
I have implemented my version of checking uppercase and lowercase in the string. It supports Unicode characters. Feedback will be highly appreciated. 

https://github.com/zestframework/Zest_Framework/issues/247

### CODE REVIEW

**Comment by peter279k** [comment]
Duplicated PR #258.

And it seems that using the `preg_match` to accomplish the `hasUppercase` and `hasLowercase` methods.

**Comment by hasukmistry** [comment]
@peter279k I thought preg_match will be quick to perform the operation. Although I am open to suggestions here. If I can make my code better.

**Comment by peter279k** [comment]
Hi @hasukmistry, thanks for your reply.

It makes sense and I close PR #258.

Could you add more tests for these methods? And it can make their behaviors reliable :).

Such as adding the English uppercase/lowercase strings.

**Comment by lablnet** [comment]
@hasmukhmistry13  thanks you so much for your time to contribute really appropriated

You're most welcome to contribute more...

**Comment by hasukmistry** [comment]
@peter279k @Lablnet I will try to add more tests for these methods. And create another PR afterward.

**Pull request merged**
