### PR TITLE
Avoid session hijacking

### PR DESCRIPTION
**Pull request by lablnet**

### CODE REVIEW

**Comment by Maikuolan** [comment]
`session_regenerate_id(); //Aviod session hijacking`

( Aviod -> Avoid )

**Comment by lablnet** [comment]
@Maikuolan  thanks for your response
You can help to solve this as soon as possible
`session_regenerate_id()` i think about to use this but i am not sure, where to use like when session starts /user login or destroy/logout/unset?

**Review by peter279k — COMMENTED** [review]
Using the `session_regenerate_id` after the user sign out.

**Review by peter279k — APPROVED** [review]

**Comment by lablnet** [comment]
Thanks @peter279k  and @Maikuolan

**Comment by peter279k** [comment]
To avoid session hijacking, consider following code:

```php
if($_SERVER['REMOTE_ADDR'] !== $_SESSION['LAST_REMOTE_ADDR'] || $_SERVER['HTTP_USER_AGENT'] !== $_SESSION['LAST_USER_AGENT']) {
   session_destroy();
}
session_regenerate_id();
$_SESSION['LAST_REMOTE_ADDR'] = $_SERVER['REMOTE_ADDR'];
$_SESSION['LAST_USER_AGENT'] = $_SERVER['HTTP_USER_AGENT'];
```

The IP address is changed or `User-Agent` header is different.

We should be forced to let user sign out and destroy and regenerate session id.

Perhaps this will be an attacker try to get another session to try to do login work.

**Comment by lablnet** [comment]
Yes so i think we need to store the user_agent and ip address in sessions

and in our `User` class we create method named `needRelogin()`
so we can used this method

Is i am right

**Pull request merged**
