### PR TITLE
Fix typos + wording.

### PR DESCRIPTION
**Pull request by Maikuolan**

### CODE REVIEW

**Comment by Maikuolan** [comment]
@peter279k @Lablnet Review requested. :-)

(( I built a simple script earlier today, to scan repositories for possible typos, to make life easier. I needed something to test it with. 😛 Changes and commits were done manually, but I used this script to find the typos in the first place. ))

**Comment by Maikuolan** [comment]
Not sure why __codecov/patch__ doesn't like these commits. Report page is difficult to understand. I understand there is a +1 of.. something.. but I'm not sure how to get more information from that.

**Review by peter279k — APPROVED** [review]
@Maikuolan, thank you for your fixing typo.

I appreciate your help and I think we can ignore the `codecov/patch` because these changes will not effect the diff code coverage.

Every fixing typo changes looks good!

Thank you for your help again!

**Comment by peter279k** [comment]
BTW, could you squash all commits to one commit?

And I think this can let us look at these changes clearly.

**Comment by Maikuolan** [comment]
> and I think we can ignore the codecov/patch because these changes will not effect the diff code coverage.

That's good news. :-)

> BTW, could you squash all commits to one commit?
>
> And I think this can let us look at these changes clearly.

Sure, I can do that. I'll sort that out now.

**Comment by Maikuolan** [comment]
Squash done.

**Review by lablnet — APPROVED** [review]

**Comment by lablnet** [comment]
@Maikuolan  Thanks you so much for your contribution appreciated, and good luck for your script.

@peter279k  thanks you too for your response

**Pull request merged**
